name: nsync_faculty
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  cherry_toast: ^1.12.0
  flutter:
    sdk: flutter
  intl: ^0.20.2
  supabase_flutter: ^2.8.4
  fl_chart: ^0.66.2
  file_picker: ^10.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
